name: mosquitto-mqtt-broker-dev
version: 0.1
summary: mosquitto broker
description: MQTT broker example
confinement: devmode 

apps:
  mosquitto:
    command: usr/sbin/mosquitto -c $SNAP/mosquitto.conf
    daemon: simple
    plugs: [network, network-bind]

parts:
  mosquitto:
    plugin: copy
    stage-packages: [mosquitto]
    files:
      mosquitto.conf: mosquitto.conf
